### ISSUE TITLE
Modify the RockNSM installer to place GeoIP data on the server in concert with Logstash

### ISSUE THREAD

**Issue by tfplenum** [tfplenum/rock#6] opened 2018-01-05 13:21 UTC
<a href="https://github.com/grantcurell"><img src="https://avatars2.githubusercontent.com/u/1595564?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [grantcurell](https://github.com/grantcurell)**
_Friday Dec 29, 2017 at 16:31 GMT_
_Originally opened as https://github.com/grantcurell/rock/issues/20_

----

Title says it all - as we're building out the role-based rocknsm installer, we need to configure the build to place GeoIP data in logstash in a centralized location.

**Comment by todd8152** [comment] 2018-01-10 16:26
Logstash includes the free GeoIP databases for ASN and City.  This should be sufficient.  If we want to update the GeoIP databases independently of Logstash then we can create a maintenance task/role for downloading the most current database without upgrading Logstash.

**Comment by grantcurell** [comment] 2018-01-20 21:17
We need to actually load maps to make this meaningful.

**Comment by grantcurell** [comment] 2018-01-20 21:18
This piece is complete and this is now a duplicate of #2

**Closed by grantcurell** 2018-01-20 21:18 UTC
Labels: intermediate
